spring:
  data:
    mongodb:
      uri: mongodb://rootuser:rootpass@localhost:27017
#      username: rootuser
#      password: rootpass
      database: users
  kafka:
    bootstrap-servers: localhost:9092