server:
  port: 25580
spring:
  data:
    mongodb:
      uri: mongodb://rootuser:rootpass@localhost:27017
#      username: rootuser
#      password: rootpass
      database: users
  kafka:
    bootstrap-servers: localhost:9092
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8080/realms/My-Realm/protocol/openid-connect/certs

